// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dbn_sample_gaussian_cpp
NumericMatrix dbn_sample_gaussian_cpp(int n_samples, int max_time, int n_vars, List plan_0, List plan_t);
RcppExport SEXP _DynamicBayesianNetwork_dbn_sample_gaussian_cpp(SEXP n_samplesSEXP, SEXP max_timeSEXP, SEXP n_varsSEXP, SEXP plan_0SEXP, SEXP plan_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< List >::type plan_0(plan_0SEXP);
    Rcpp::traits::input_parameter< List >::type plan_t(plan_tSEXP);
    rcpp_result_gen = Rcpp::wrap(dbn_sample_gaussian_cpp(n_samples, max_time, n_vars, plan_0, plan_t));
    return rcpp_result_gen;
END_RCPP
}
// dbn_sample_discrete_cpp
IntegerMatrix dbn_sample_discrete_cpp(int n_samples, int max_time, int n_vars, IntegerVector n_levels, List plan_0, List plan_t);
RcppExport SEXP _DynamicBayesianNetwork_dbn_sample_discrete_cpp(SEXP n_samplesSEXP, SEXP max_timeSEXP, SEXP n_varsSEXP, SEXP n_levelsSEXP, SEXP plan_0SEXP, SEXP plan_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type max_time(max_timeSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_levels(n_levelsSEXP);
    Rcpp::traits::input_parameter< List >::type plan_0(plan_0SEXP);
    Rcpp::traits::input_parameter< List >::type plan_t(plan_tSEXP);
    rcpp_result_gen = Rcpp::wrap(dbn_sample_discrete_cpp(n_samples, max_time, n_vars, n_levels, plan_0, plan_t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DynamicBayesianNetwork_dbn_sample_gaussian_cpp", (DL_FUNC) &_DynamicBayesianNetwork_dbn_sample_gaussian_cpp, 5},
    {"_DynamicBayesianNetwork_dbn_sample_discrete_cpp", (DL_FUNC) &_DynamicBayesianNetwork_dbn_sample_discrete_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DynamicBayesianNetwork(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
