# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbn_sample_gaussian_cpp <- function(n_samples, max_time, n_vars, plan_0, plan_t) {
    .Call(`_DynamicBayesianNetwork_dbn_sample_gaussian_cpp`, n_samples, max_time, n_vars, plan_0, plan_t)
}

dbn_sample_discrete_cpp <- function(n_samples, max_time, n_vars, n_levels, plan_0, plan_t) {
    .Call(`_DynamicBayesianNetwork_dbn_sample_discrete_cpp`, n_samples, max_time, n_vars, n_levels, plan_0, plan_t)
}

